FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONPATH=/app
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# kopiujemy pakiet z conid_sync
COPY agent ./agent

# kod aplikacji i konfiguracje
COPY app ./app
COPY config ./config

CMD ["python","app/main.py"]
