USDJPY:
  kind: forex
  conId: 15016059
  secType: "CASH"
  symbol: "USD"         # base
  exchange: "IDEALPRO"
  currency: "JPY"       # quote
  duration: "30 D"
  barSize: "1 hour"
  whatToShow: "MIDPOINT"

USDPLN:
  kind: forex
  conId: 34831481
  secType: "CASH"
  symbol: "USD"         # base
  exchange: "IDEALPRO"
  currency: "PLN"       # quote
  duration: "30 D"
  barSize: "1 hour"
  whatToShow: "MIDPOINT"
